import { pathways, brand, grade, wordCount } from './content.js';
import { readState, saveState } from './store.js';
const main = document.querySelector('main');
let state = readState();
state.completed = Array.isArray(state.completed) ? state.completed.filter(x => typeof x === 'string') : [];
state.results = Array.isArray(state.results) ? state.results.filter(x => x && pathways[x.path] && Number.isFinite(x.score)) : [];
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const persist = () => saveState(state);
const button = (href, label, secondary = false) => `<a class="button ${secondary ? 'secondary' : ''}" href="${href}">${label}</a>`;
const done = p => p.lessons.filter(l => state.completed.includes(l.id)).length;
function account() {
  document.querySelector('#account').innerHTML = state.user ? `<button class="text-button" id="logout">خروج من التجربة</button>` : button('#login', 'دخول تجريبي', true);
  document.querySelector('#logout')?.addEventListener('click', () => { delete state.user; persist(); location.hash = '#home'; render(); });
}
function home() {
  main.innerHTML = `<section class="hero"><div><span class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>إنجليزيتك أقوى.<br><span>مستقبلك أقرب.</span></h1><p>مساحة للتعلّم والممارسة وبناء الثقة.<br>اختر مسارك، وابدأ بخطوة صغيرة اليوم.</p><div class="actions">${button('#path/step', 'ابدأ مسار STEP ←')}${button('#path/ielts', 'استكشف IELTS', true)}</div><p class="small">دروس قصيرة • تطبيق مباشر • تقدّم يمكنك متابعته</p></div><div class="study-art" aria-hidden="true"><div class="orbit"></div><div class="art-label">LEARN. PRACTISE. GROW.</div><div class="book book-back">IELTS <span>Find your voice.</span></div><div class="book">STEP <span>One step closer.</span></div><div class="art-note">A little practice.<br>A lot of possibility.</div></div></section>
  <section class="section"><div class="section-heading"><div><span class="eyebrow">CHOOSE YOUR PATH</span><h2>رحلتك تبدأ من هنا</h2></div><span class="muted">مساران، وهدف واحد: تقدّمك</span></div><div class="path-grid">${Object.entries(pathways).map(([key,p]) => `<article class="path-card ${key}"><div class="card-top"><span class="tag">${key === 'step' ? '01' : '02'} / LEARNING PATH</span><span class="pill">${p.lessons.length} دروس</span></div><h3 dir="ltr">${p.title}</h3><h4>${p.subtitle}</h4><p>${p.description}</p><div class="skills" dir="ltr">${p.skills.map(s=>`<span>${s}</span>`).join('')}</div>${button('#path/'+key, 'اكتشف المسار ←', true)}</article>`).join('')}</div></section>
  <section class="how"><h2>من التعلّم إلى الإنجاز</h2><div><p><b>01 · تعلّم</b><span>فكرة واضحة وأمثلة مفيدة.</span></p><p><b>02 · جرّب</b><span>طبّق ما تعلّمته فورًا.</span></p><p><b>03 · تطوّر</b><span>راجع الشرح وتابع تقدمك.</span></p></div></section>`;
}
function login() {
 main.innerHTML = `<section class="login-layout"><div><span class="eyebrow">WELCOME TO YOUR ACADEMY</span><h1>أهلًا بك في<br>خطوتك القادمة.</h1><p>جرّب المسارات، تعلّم شيئًا جديدًا، وتابع إنجازك.</p><div class="notice">هذه تجربة محلية بدون حساب أو كلمة مرور. التقدم مشترك بين مستخدمي هذا المتصفح ولا ينتقل بين الأجهزة. لا تدخل بيانات حساسة.</div></div><form id="login-form" class="panel"><h2>دخول تجريبي</h2><label for="name">اسم العرض أو اسم مستعار</label><input id="name" name="name" maxlength="50" required autocomplete="nickname" placeholder="كيف نناديك؟"><label for="level">مستواك الحالي</label><select id="level" name="level"><option value="beginner">مبتدئ</option><option value="intermediate">متوسط</option><option value="advanced">متقدم</option></select><p class="small">يُحفظ اختيارك فقط؛ المحتوى التمهيدي نفسه لجميع المستويات.</p><button class="button" type="submit">ابدأ التعلّم ←</button></form></section>`;
 document.querySelector('#login-form').onsubmit = e => { e.preventDefault(); const name = e.target.elements.name.value.trim(); if (!name) { e.target.elements.name.setCustomValidity('أدخل اسمًا غير فارغ'); e.target.elements.name.reportValidity(); return; } state.user = { name, level: e.target.elements.level.value }; persist(); location.hash = '#progress'; };
 document.querySelector('#name').oninput = e => e.target.setCustomValidity('');
}
function path(key) {
 const p = pathways[key];
 main.innerHTML = `<section class="page-heading"><span class="eyebrow">YOUR ${p.title} PATHWAY</span><h1>${p.title} <span>· ${p.subtitle}</span></h1><p>${p.label}</p><div class="progress-track"><div style="width:${done(p)/p.lessons.length*100}%"></div></div><p class="small">${done(p)} من ${p.lessons.length} دروس مكتملة</p></section><div class="course-layout"><section><h2>تعلّم بالوتيرة المناسبة لك</h2>${p.lessons.map((l,i)=>`<article class="lesson panel"><div class="lesson-number">0${i+1}</div><div><span class="eyebrow">${l.skill} · ${l.minutes} MIN</span><h3 dir="ltr">${l.title}</h3></div>${button('#lesson/'+key+'/'+l.id, state.completed.includes(l.id) ? '✓ مراجعة الدرس' : 'ابدأ الدرس', true)}</article>`).join('')}</section><aside class="panel practice"><span class="eyebrow">PUT IT INTO PRACTICE</span><h2>حان وقت التجربة</h2><p>تدريب تمهيدي من ${p.questions.length} أسئلة، مع تصحيح وشرح لكل إجابة.</p>${button('#quiz/'+key, 'ابدأ التدريب ←')}<p class="small">ليس اختبارًا رسميًا أو محاكاة كاملة؛ لا تعادل نتيجته درجة STEP أو IELTS.</p>${key==='ielts' ? button('#writing', 'مساحة الكتابة', true): ''}</aside></div>`;
}
function lesson(key, id) {
 const l = pathways[key].lessons.find(l=>l.id === id);
 if (!l) return notFound();
 main.innerHTML = `<section class="reading-width">${button('#path/'+key,'→ العودة للمسار',true)}<article class="panel lesson-content"><span class="eyebrow">${l.skill} · ${l.minutes} MIN</span><h1 dir="ltr">${l.title}</h1><div lang="en" dir="ltr"><p>${l.body}</p><h2>Examples</h2>${l.examples.map(x=>`<p class="example">${x}</p>`).join('')}</div><button id="complete" class="button">${state.completed.includes(id) ? '✓ أُكمل الدرس' : 'أنهيت الدرس ✓'}</button></article></section>`;
 document.querySelector('#complete').onclick=()=>{ if(!state.completed.includes(id)) state.completed.push(id); persist(); location.hash='#path/'+key; };
}
function quiz(key) {
 const p=pathways[key];
 main.innerHTML=`<section class="reading-width"><span class="eyebrow">${p.title} · STARTER PRACTICE</span><h1>اختبر فهمك</h1><p>أجب عن جميع الأسئلة ثم راجع الإجابات والشرح.</p><form id="quiz-form">${p.questions.map((q,i)=>`<fieldset class="panel question" lang="en" dir="ltr"><legend>Question ${i+1} of ${p.questions.length}</legend>${q.passage?`<p class="passage">${q.passage}</p>`:''}<h2>${q.prompt}</h2>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${o}</span></label>`).join('')}</fieldset>`).join('')}<button class="button" type="submit">إظهار النتيجة والشرح</button></form></section>`;
 document.querySelector('#quiz-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target); const answers=p.questions.map((_,i)=>Number(data.get('q'+i))); const score=grade(p.questions,answers); state.results.push({path:key,score,total:p.questions.length,date:new Date().toISOString()});state.results=state.results.slice(-100);persist();main.innerHTML=`<section class="reading-width"><div class="result-banner"><span class="eyebrow">PRACTICE COMPLETE</span><h1>${score} / ${p.questions.length}</h1><p>كل محاولة فرصة جديدة للتعلّم.</p><p class="small">نتيجة تدريب تمهيدي وليست درجة رسمية أو تحديدًا للمستوى.</p></div>${p.questions.map((q,i)=>`<article class="panel review" dir="ltr" lang="en"><span class="pill">${answers[i]===q.answer?'✓ Correct':'↻ Review'}</span><h2>${i+1}. ${q.prompt}</h2><p>Your answer: ${q.options[answers[i]]}</p><p><b>Correct answer: ${q.options[q.answer]}</b></p><p>${q.explanation}</p></article>`).join('')}<div class="actions">${button('#progress','عرض تقدمي')}${button('#path/'+key,'العودة للمسار',true)}</div></section>`;main.focus();window.scrollTo(0,0);};
}
function progress() {
 const total=Object.values(pathways).reduce((n,p)=>n+done(p),0);
 main.innerHTML=`<section class="page-heading"><span class="eyebrow">YOUR LEARNING JOURNEY</span><h1>أهلًا ${escape(state.user?.name || 'بك')}، <span>واصل التقدّم.</span></h1><p>تقدمك محفوظ في هذا المتصفح فقط.</p></section><div class="stats"><div class="panel"><strong>${total} / ${Object.values(pathways).reduce((n,p)=>n+p.lessons.length,0)}</strong><span>دروس مكتملة</span></div><div class="panel"><strong>${state.results.length}</strong><span>محاولات تدريب محفوظة</span></div><div class="panel"><strong>خطوتك التالية</strong><a href="#path/${done(pathways.step)<pathways.step.lessons.length?'step':'ielts'}">تابع التعلّم ←</a></div></div><section class="section"><h2>مساراتك</h2><div class="path-grid">${Object.entries(pathways).map(([key,p])=>`<article class="panel"><h3>${p.title}</h3><p>${done(p)} / ${p.lessons.length} دروس</p>${button('#path/'+key,'تابع المسار',true)}</article>`).join('')}</div><h2>سجل التدريبات</h2>${state.results.length?`<div class="table-wrap"><table><thead><tr><th>المسار</th><th>النتيجة</th><th>التاريخ</th></tr></thead><tbody>${[...state.results].reverse().map(r=>`<tr><td>${pathways[r.path].title}</td><td>${escape(r.score)} / ${escape(r.total)}</td><td>${escape(new Date(r.date).toLocaleDateString('ar-SA'))}</td></tr>`).join('')}</tbody></table></div>`:`<div class="panel"><p>لم تبدأ تدريبًا بعد. اختر مسارًا لتجربة أول خمسة أسئلة.</p>${button('#path/step','استكشف STEP',true)}</div>`}<button id="reset" class="text-button danger">مسح التقدم والمسودة من هذا المتصفح</button></section>`;
 document.querySelector('#reset').onclick=()=>{if(confirm('هل تريد مسح تقدمك ونتائجك ومسودة الكتابة؟')){state.completed=[];state.results=[];state.draft='';persist();progress();}};
}
function writing(){
 main.innerHTML=`<section class="reading-width"><span class="eyebrow">IELTS · WRITING STUDIO</span><h1>مساحة للتعبير</h1><p>تدريب كتابة مستقل. يُحفظ النص على جهازك تلقائيًا.</p><div class="panel"><h2 dir="ltr" lang="en">Some people believe students learn better in groups. Others prefer studying alone. Discuss both views and give your opinion.</h2><label for="draft">اكتب مقالك بالإنجليزية (هدف تدريبي: 250 كلمة على الأقل)</label><textarea id="draft" dir="ltr" lang="en" rows="14" maxlength="20000" placeholder="Start with your introduction…">${escape(typeof state.draft==='string'?state.draft:'')}</textarea><p id="words" aria-live="polite"></p><p class="notice">هذه المساحة تعد الكلمات وتحفظ المسودة فقط. لا توفر تصحيحًا بالذكاء الاصطناعي أو درجة IELTS.</p><h3>راجع كتابتك</h3><p>هل ناقشت الرأيين؟ هل أوضحت رأيك؟ هل دعمت أفكارك بأمثلة؟</p></div>${button('#path/ielts','→ العودة لمسار IELTS',true)}</section>`;
 const draft=document.querySelector('#draft');const count=()=>document.querySelector('#words').textContent=`${wordCount(draft.value)} كلمة / هدف 250 كلمة`;count();draft.oninput=()=>{state.draft=draft.value;persist();count();};
}
function notFound(){main.innerHTML=`<section class="page-heading"><h1>الصفحة غير موجودة</h1>${button('#home','العودة للرئيسية')}</section>`;}
function render(){account();const [page,key,id]=(location.hash.slice(1)||'home').split('/');if(page==='home')home();else if(page==='login')login();else if(page==='progress')progress();else if(page==='writing')writing();else if(pathways[key]&&page==='path')path(key);else if(pathways[key]&&page==='lesson')lesson(key,id);else if(pathways[key]&&page==='quiz')quiz(key);else notFound();document.title=`${brand.name} | ${page==='home'?'تعلّم بثقة':page==='progress'?'تقدمي':pathways[key]?.title||'ابدأ رحلتك'}`;document.querySelectorAll('nav a').forEach(a=>a.toggleAttribute('aria-current',a.getAttribute('href')===(location.hash||'#home')));window.scrollTo(0,0);main.focus();}
window.addEventListener('hashchange',render);render();
